# Generated by Django 3.2.23 on 2024-01-08 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('public_chat', '0002_alter_publicchatroom_online_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='publicchatroom',
            name='online_users',
        ),
        migrations.RemoveField(
            model_name='publicroomchatmessage',
            name='room',
        ),
        migrations.RemoveField(
            model_name='publicroomchatmessage',
            name='user',
        ),
        migrations.DeleteModel(
            name='PublicRoomChatMessageManager',
        ),
        migrations.DeleteModel(
            name='PublicChatRoom',
        ),
        migrations.DeleteModel(
            name='PublicRoomChatMessage',
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public_chat.room'),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
